CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id BIGINT,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    completed BOOLEAN NOT NULL,
    due_date DATETIME,
    priority INTEGER NOT NULL,
    owner BIGINT
);

CREATE TABLE task_tag (
    task_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL
);

ALTER TABLE task_tag 
ADD CONSTRAINT pk_task_tag 
PRIMARY KEY (task_id, tag_id);

ALTER TABLE task_tag 
ADD CONSTRAINT fk_task_tag_task_id
FOREIGN KEY (task_id) REFERENCES task(id);

ALTER TABLE task_tag 
ADD CONSTRAINT fk_task_tag_tag_id
FOREIGN KEY (tag_id) REFERENCES tag(id);