ALTER TABLE task_tag DROP CONSTRAINT IF EXISTS fk_task_tag_task_id;
ALTER TABLE task_tag DROP CONSTRAINT IF EXISTS fk_task_tag_tag_id;
ALTER TABLE task_tag DROP CONSTRAINT IF EXISTS pk_task_tag;
DROP TABLE IF EXISTS task_tag;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS tag;